### ISSUE TITLE
In master branch, LICENSE file contradicts Readme.md

### ISSUE THREAD

**Issue by daveloyall** [franzinc/xmlutils#1]
https://github.com/franzinc/xmlutils/blob/master/LICENSE

vs 

https://github.com/franzinc/xmlutils/blob/master/README.md#license

**Comment by OLDlayeratwork** [comment]
Thanks for noticing it.  I'll fix it up shortly.

**Comment by OLDlayeratwork** [comment]
A fixed commit will appear here within 24 hours.
